# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site Settings
title: Sakithma Rajapaksha
description: >- # this means to ignore newlines until "baseurl:"
  Biotechnology Undergraduate | SLIIT | Passionate about Science & Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sakithma.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sakithma
github_username: sakithma

# Author Information
author:
  name: Sakithma Rajapaksha
  email: sakithma@example.com
  bio: "Biotechnology Undergraduate at SLIIT | Passionate about Science & Technology"
  avatar: /assets/images/profile.jpg

# Build Settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Custom CSS
custom_css:
  - /assets/css/style.css

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /#about
  - title: Education
    url: /#education
  - title: Projects
    url: /#projects
  - title: Skills
    url: /#skills
  - title: Contact
    url: /#contact

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Social Media Links
social:
  name: Sakithma Rajapaksha
  links:
    - https://github.com/sakithma
    - mailto:sakithma@example.com
    - https://linkedin.com/in/sakithma

# SEO
seo:
  type: Person
  name: Sakithma Rajapaksha
  job_title: Biotechnology Undergraduate
  description: First-year Biotechnology student at SLIIT with interests in science, technology, and community service
  image: /assets/images/profile.jpg

# Portfolio Settings
portfolio:
  hero_title: "Hello, I'm Sakithma Rajapaksha"
  hero_subtitle: "Biotechnology Undergraduate | SLIIT"
  hero_description: "Passionate about Science & Technology"
  
# Theme Customization
minima:
  skin: dark
  social_links:
    github: sakithma
    linkedin: sakithma
    email: sakithma@example.com
